use_frameworks!

target 'CryptoNewsApi_Example' do
  pod 'CryptoNewsApi', :path => '../'

  target 'CryptoNewsApi_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
